### ISSUE TITLE
No module named 'qiskit_nature.second_q'.

### ISSUE THREAD

**Issue by jeb12301** [Qiskit/qiskit-nature#810] opened 2022-08-27 14:58 UTC
### Environment

- **Qiskit Nature version**:
- **Python version**: 
- **Operating system**: 

### What is happening?

Python returns: No module named 'qiskit_nature.second_q'. 

I installed qiskit_nature using pip3 install 'qiskit[nature]' as described in the documentation. 

I am currently using macos. My python version is 3.9.12

Typing: import qiskit_nature; dir(qiskit_nature) returns:
['ListOrDictType', 'QiskitNatureError', 'UnsupportMethodError', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'exceptions', 'logging', 'settings', 'version']

### How can we reproduce the issue?

<img width="722" alt="image" src="https://user-images.githubusercontent.com/98257374/187035695-5f490674-d909-4320-b66e-0b1e07e85b30.png">

### What should happen?

Should successfully import

**Comment by woodsp-ibm** [comment] 2022-08-27 17:31
This is a duplicate of #811 which I answered. I am therefore closing this duplicate - see #811 for answer.

**Closed by woodsp-ibm** 2022-08-27 17:31 UTC
